# Generated by Django 2.2.1 on 2019-06-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genome_size', models.CharField(max_length=30)),
                ('repeat', models.CharField(max_length=30)),
                ('tax_ID', models.CharField(max_length=30)),
                ('dist', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='')),
                ('uploadText', models.TextField()),
            ],
        ),
    ]
