# Generated by Django 2.2.1 on 2019-06-06 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='uploadText',
        ),
    ]
