# Generated by Django 2.2.1 on 2019-06-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='')),
                ('uploadText', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='uploadForm',
        ),
    ]
